#!/usr/bin/env bash
# thinkpad-client wizard — stand up a roaming ThinkPad (Debian) as a Larry thin client.
# Generated by /wizard from tower/thinkpad-setup.md. Deterministic; nothing here talks to an
# LLM. The only network calls are package installs and the URLs YOU open / sign in to.
# Re-run any time: completed steps are skipped (state in ~/.thinkpad-client.wizard-state).
#
#   READ THIS SCRIPT before running it.  Then:  bash thinkpad-client.sh
set -euo pipefail

STATE="${WIZARD_STATE:-$HOME/.thinkpad-client.wizard-state}"; touch "$STATE"
ZENV="$HOME/.config/zsh/.zshenv"
REPO="${LARRY_SETUP:-$HOME/larry-setup}"
LARRY="https://larry.home.arpa:11443"

done_step(){ grep -qxF "$1" "$STATE"; }
mark(){ grep -qxF "$1" "$STATE" || echo "$1" >>"$STATE"; }

c_ok=$'\033[32m'; c_hd=$'\033[1;36m'; c_no=$'\033[31m'; c_wn=$'\033[33m'; c_z=$'\033[0m'
step(){ printf '\n%s[%s]%s %s\n' "$c_hd" "$1" "$c_z" "$2"; }
ok(){   printf '  %s✓%s %s\n'  "$c_ok" "$c_z" "$1"; }
warn(){ printf '  %s!%s %s\n'  "$c_wn" "$c_z" "$1"; }
die(){  printf '  %s✗%s %s\n'  "$c_no" "$c_z" "$1"; exit 1; }
say(){  printf '  %s\n' "$1"; }
ask(){    local v; read -rp  "  $1 " v; printf '%s' "$v"; }
secret(){ local v; read -rsp "  $1 " v; echo; printf '%s' "$v"; }
yes(){    local v; read -rp  "  $1 [y/N] " v; [ "${v:-}" = y ] || [ "${v:-}" = Y ]; }
pause(){  read -rp "  ↵ press enter when done… " _; }
open_url(){ { command -v xdg-open >/dev/null && xdg-open "$1"; } 2>/dev/null \
         || { command -v open >/dev/null && open "$1"; } 2>/dev/null \
         || echo "     open this URL: $1"; }
# append a marked block to .zshenv exactly once
zappend(){ # $1 = unique marker, $2 = block
  mkdir -p "$(dirname "$ZENV")"; touch "$ZENV"
  grep -qF "$1" "$ZENV" || printf '\n%s\n' "$2" >>"$ZENV"
}

printf '%s╭─ ThinkPad → Larry thin-client wizard ─────────────────────────╮%s\n' "$c_hd" "$c_z"
say "Turns tower/thinkpad-setup.md into a guided, resumable install."
say "Steps marked [HUMAN] need you (copy a cert, sign in). Rest is automatic."
say "State file: $STATE  (delete it to start over)"

# ── 0. preflight ───────────────────────────────────────────────────────────────
step 0 "Preflight"
command -v apt-get >/dev/null || warn "not a Debian/apt box — commands below assume apt; adapt as needed."
[ "$(id -u)" -ne 0 ] || die "run as your normal user, not root (it will sudo when needed)."
ok "user=$(whoami)  home=$HOME  setup-repo target=$REPO"

# ── 1. base tools ────────────────────────────────────────────────────────────────
step 1 "Base packages (build tools, git, python, zsh)"
if done_step base; then ok "already done"; else
  sudo apt-get update
  sudo apt-get install -y build-essential git curl unzip python3 python3-venv ca-certificates zsh
  ok "installed"; mark base
fi

# ── 2. zsh + ZDOTDIR ─────────────────────────────────────────────────────────────
step 2 "zsh as login shell + ZDOTDIR=~/.config/zsh"
if done_step zsh; then ok "already done"; else
  mkdir -p "$HOME/.config/zsh"; touch "$ZENV"
  echo 'export ZDOTDIR="$HOME/.config/zsh"' | sudo tee /etc/zsh/zshenv >/dev/null
  if [ "$SHELL" != "$(command -v zsh)" ]; then
    chsh -s "$(command -v zsh)" && ok "login shell -> zsh (effective next login)" \
      || warn "chsh failed — set zsh as login shell manually later"
  fi
  ok "env file is $ZENV (NOT ~/.zshrc)"; mark zsh
fi

# ── 3. clone setup repo (needed for provider + tooling) ──────────────────────────
step 3 "Clone the larry-setup repo   [HUMAN: SSH vs HTTPS]"
if [ -d "$REPO/.git" ]; then ok "already cloned at $REPO"; mark repo
elif done_step repo; then ok "marked done"; else
  say "SSH needs a key on GitHub; HTTPS will prompt for a token."
  if yes "Use SSH (git@github.com)?"; then url="git@github.com:drs76/larry-setup.git"
  else url="https://github.com/drs76/larry-setup.git"; fi
  git clone "$url" "$REPO" || die "clone failed — check network/credentials, then re-run"
  ok "cloned to $REPO"; mark repo
fi

# ── 4. DNS to Larry ──────────────────────────────────────────────────────────────
step 4 "Resolve larry.home.arpa (Pi-hole on the home LAN)"
if getent hosts larry.home.arpa >/dev/null; then
  ok "resolves -> $(getent hosts larry.home.arpa | awk '{print $1}')"; mark dns
else
  warn "larry.home.arpa does NOT resolve — you're off the home LAN, or Pi-hole isn't your DNS."
  say "pi/local builds need Larry; Claude escalation works anywhere. Step 12 sets up WireGuard."
  yes "Continue anyway (finish now, connect to Larry later)?" || die "stopping — rejoin LAN and re-run"
  mark dns_deferred
fi

# ── 5. HomeLab CA trust ──────────────────────────────────────────────────────────
step 5 "Trust the HomeLab CA   [HUMAN: supply ca.crt]"
if done_step ca; then ok "already done"
elif ! getent hosts larry.home.arpa >/dev/null; then warn "skipped — no Larry reachable yet (do this once on-LAN/WG)"
else
  if curl -sS "$LARRY/api/version" >/dev/null 2>&1; then ok "CA already trusted (curl works without -k)"; mark ca
  else
    say "Copy the PUBLIC ca.crt onto this box (scp from the deb box or bring on USB)."
    say "  example:  scp deb.home.arpa:/path/to/ca.crt ~/ca.crt   (never copy the CA *key*)"
    p="$(ask 'Path to ca.crt (default ~/ca.crt):')"; p="${p:-$HOME/ca.crt}"
    [ -f "$p" ] || die "not found: $p — copy it over, then re-run"
    sudo cp "$p" /usr/local/share/ca-certificates/homelab-ca.crt
    sudo update-ca-certificates
    curl -sS "$LARRY/api/version" >/dev/null 2>&1 \
      && { ok "chain verified over the proxy (no -k needed)"; mark ca; } \
      || die "still not trusted — check the cert is the HomeLab ROOT, then re-run"
  fi
fi

# ── 6. Node 22 + pi + provider ───────────────────────────────────────────────────
step 6 "Node 22, pi coding agent, Larry provider"
if done_step pi; then ok "already done"; else
  nv="$(node -v 2>/dev/null | sed 's/^v//' | cut -d. -f1 || echo 0)"
  if [ "${nv:-0}" -lt 22 ]; then
    say "installing Node 22 (Debian stable ships 20; pi needs >=22.19)…"
    curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
    sudo apt-get install -y nodejs
  fi
  node -v | grep -q '^v2[2-9]' || die "Node still <22 — fix, then re-run"; ok "node $(node -v)"
  npm config set prefix "$HOME/.npm-global"
  npm install -g @earendil-works/pi-coding-agent
  mkdir -p "$HOME/.pi/agent"
  cp "$REPO/tower/ollama-provider.ts" "$HOME/.pi/" \
    || die "provider file missing at $REPO/tower/ollama-provider.ts (is the repo cloned? step 3)"
  ok "provider copied (0.81 createProvider form — do not hand-edit to legacy)"
  zappend "use-system-ca" '# ---------- Node / pi ----------
export NODE_OPTIONS="--use-system-ca"
export PATH="$HOME/.npm-global/bin:$HOME/.local/bin:$PATH"'
  export NODE_OPTIONS="--use-system-ca"; export PATH="$HOME/.npm-global/bin:$HOME/.local/bin:$PATH"
  # register the provider so plain `pi` loads it (merge, don't clobber existing settings)
  python3 - "$HOME/.pi/agent/settings.json" <<'PY'
import json,sys,os
p=sys.argv[1]; d={}
if os.path.exists(p):
    try: d=json.load(open(p))
    except Exception: d={}
ext=d.get("extensions",[])
if "~/.pi/ollama-provider.ts" not in ext: ext.append("~/.pi/ollama-provider.ts")
d["extensions"]=ext; d.setdefault("defaultModel","qwen3-coder:30b")
json.dump(d,open(p,"w"),indent=2)
print("  settings.json updated:",p)
PY
  if getent hosts larry.home.arpa >/dev/null; then
    pi --list-models 2>/dev/null | grep -q qwen3-coder \
      && ok "pi sees Larry's models over HTTPS" \
      || warn "pi didn't list models — check NODE_OPTIONS + CA (troubleshooting in the doc)"
  else warn "Larry unreachable — skipping pi model check"; fi
  mark pi
fi

# ── 7. Claude Code ───────────────────────────────────────────────────────────────
step 7 "Claude Code + sign-in   [HUMAN]"
if done_step claude; then ok "already done"; else
  command -v claude >/dev/null || curl -fsSL https://claude.ai/install.sh | bash
  export PATH="$HOME/.local/bin:$PATH"
  claude --version >/dev/null 2>&1 || die "claude not on PATH after install"
  say "Sign in once now: open a new terminal, run 'claude', follow the auth prompt."
  say "(Claude uses the public CA — works on or off the home LAN. This is the escalation backend.)"
  pause; ok "claude $(claude --version 2>/dev/null | head -1)"; mark claude
fi

# ── 8. workflow tooling + env ────────────────────────────────────────────────────
step 8 "Workflow CLIs, prompts, slash-commands, env"
if done_step tooling; then ok "already done"; else
  mkdir -p "$HOME/.local/bin" "$HOME/.pi/agent/prompts" "$HOME/.claude/commands" "$HOME/projects/prototypes"
  cp "$REPO"/tooling/{alw,gow,csw} "$HOME/.local/bin/" && chmod +x "$HOME"/.local/bin/{alw,gow,csw}
  # pi prompt-templates (include the ones that exist; wizard.md/route files are optional)
  for f in al-route.md go-route.md cs-route.md spec.md handover.md warplan.md bc-agent.md wizard.md; do
    [ -f "$REPO/tooling/$f" ] && cp "$REPO/tooling/$f" "$HOME/.pi/agent/prompts/"
  done
  # Claude slash-commands (the *-claude.md entries install under their bare name)
  for pair in warplan bc-agent spec wizard; do
    src="$REPO/tooling/$pair-claude.md"; [ -f "$src" ] || src="$REPO/tooling/$pair.md"
    [ -f "$src" ] && cp "$src" "$HOME/.claude/commands/$pair.md"
  done
  zappend "Larry workflow (ThinkPad client)" '# ---------- Larry workflow (ThinkPad client) ----------
export RUN_BUILD="$HOME/larry-setup/pipeline/run-build.py"
export RUN_BUILD_GO="$HOME/larry-setup/pipeline/run-build-go.py"
export RUN_BUILD_CS="$HOME/larry-setup/pipeline/run-build-cs.py"
export TEMPLATE="$HOME/larry-setup/templates/larry-handover.template.md"
export PROJECTS_DIR="$HOME/projects"
export PROTOTYPES_DIR="$HOME/projects/prototypes"
export PI_CODER_MODEL="ollama/qwen3-coder:30b"
export COMS_VALIDATOR_MODEL="ollama/qwen3-coder:30b"
export COMS_RELAY_MODEL="ollama/qwen3-coder:30b"'
  ok "tooling installed; workflow env appended to $ZENV"
  say "open a new shell (or 'source $ZENV'), then: alw help / gow help / csw help"
  mark tooling
fi

# ── 9. optional: Go toolchain ────────────────────────────────────────────────────
step 9 "Go toolchain (for gow) — optional"
if done_step go; then ok "already done"
elif command -v go >/dev/null; then ok "go present: $(go version | awk '{print $3}')"; mark go
elif yes "Install golang-go now?"; then sudo apt-get install -y golang-go; go version && mark go
else say "skipped"; fi

# ── 10. optional: .NET toolchain ─────────────────────────────────────────────────
step 10 ".NET 10 / C# toolchain (for csw) — optional"
if done_step dotnet; then ok "already done"
elif command -v dotnet >/dev/null; then ok "dotnet present: $(dotnet --version)"; mark dotnet
elif yes "Install .NET 10 now?"; then
  curl -fsSL https://dot.net/v1/dotnet-install.sh | bash -s -- --channel 10.0
  zappend 'dotnet PATH' 'export PATH="$HOME/.dotnet:$PATH"'
  export PATH="$HOME/.dotnet:$PATH"; dotnet --version && mark dotnet
else say "skipped"; fi

# ── 11. optional: smoke test ─────────────────────────────────────────────────────
step 11 "Smoke test the full loop (gow) — optional"
if ! getent hosts larry.home.arpa >/dev/null; then warn "skipped — needs Larry reachable"
elif ! command -v go >/dev/null; then warn "skipped — Go not installed (step 9)"
elif done_step smoke; then ok "already run"
elif yes "Run a gow smoke build now (ThinkPad scaffolds, Larry codes over HTTPS)?"; then
  export PATH="$HOME/.npm-global/bin:$HOME/.local/bin:$PATH"; export NODE_OPTIONS="--use-system-ca"
  gow new tp-smoke || true
  h="$HOME/projects/prototypes/tp-smoke/larry-handover.prompt.md"
  [ -f "$h" ] && say "edit $h with a tiny spec (e.g. GET /ping -> pong), then: gow build tp-smoke"
  say "expect RESULT: PASS. (Left interactive on purpose — run 'gow build tp-smoke' yourself.)"
  mark smoke
else say "skipped"; fi

# ── 12. optional: WireGuard roaming ──────────────────────────────────────────────
step 12 "WireGuard back home (roaming) — optional   [HUMAN: peer values]"
if done_step wg; then ok "already configured"
elif yes "Set up the WireGuard tunnel to reach Larry off-LAN?"; then
  sudo apt-get install -y wireguard
  conf=/etc/wireguard/larry.conf
  if [ -f "$conf" ]; then ok "$conf already exists — leaving it"; else
    say "Three values come from an existing working peer (phone's jellydav config / router WG UI):"
    say "  <router-wg-pubkey>, <ddns-host>:<wg-port>, and the tunnel /24 for your Address."
    warn "Wizard writes a TEMPLATE with TODO(human) markers — fill them before 'wg-quick up'."
    umask 077
    priv="$(wg genkey)"; pub="$(printf '%s' "$priv" | wg pubkey)"
    sudo tee "$conf" >/dev/null <<EOF
[Interface]
PrivateKey = $priv
Address    = 10.0.0.TODO/32          # TODO(human): next free tunnel IP (check a jellydav peer)
DNS        = 192.168.0.175           # Pi-hole (Nemesis) -> resolves larry.home.arpa

[Peer]
PublicKey  = TODO_ROUTER_WG_PUBKEY   # TODO(human): same [Peer] PublicKey as jellydav/phone
Endpoint   = TODO_DDNS_HOST:TODO_PORT# TODO(human): same public endpoint jellydav uses
AllowedIPs = 192.168.0.0/24          # split-tunnel: home LAN only (0.0.0.0/0 = full tunnel)
PersistentKeepalive = 25
EOF
    sudo chmod 600 "$conf"
    printf '\n  This box PUBLIC key (add as a router peer, AllowedIPs 10.0.0.N/32):\n    %s\n' "$pub"
    say "Then: doas/sudo wg-quick up larry ; getent hosts larry.home.arpa ; curl -sS $LARRY/api/version"
  fi
  mark wg
else say "skipped"; fi

# ── done ─────────────────────────────────────────────────────────────────────────
printf '\n%s╰─ done ────────────────────────────────────────────────────────╯%s\n' "$c_ok" "$c_z"
say "Open a NEW shell so $ZENV is loaded, then verify: alw help / gow help / csw help"
say "Not covered here (see tower/thinkpad-setup.md): AL toolchain §6, ALNvim §7, Sway §11."
say "Re-run this wizard any time — completed steps are skipped."
