#requires -Version 5.1
<#
  windows-host-client wizard — stand up a native Windows workstation (PowerShell, no WSL) as a
  Larry pipeline client. Generated by /wizard from tower/windows-host-setup.md.

  Deterministic: nothing here talks to an LLM. Network calls are package installs + the URLs / auth
  prompts YOU complete. Re-run any time — completed steps are skipped (state in
  %USERPROFILE%\.windows-host.wizard-state).

  READ THIS SCRIPT first. Some steps (CA import, machine env, symlinks) need an ELEVATED shell:
      Start an admin PowerShell, then:  Set-ExecutionPolicy -Scope Process Bypass; .\windows-host-client.ps1
#>
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$State = Join-Path $env:USERPROFILE '.windows-host.wizard-state'
if (-not (Test-Path $State)) { New-Item -ItemType File -Path $State -Force | Out-Null }
$Repo   = if ($env:LARRY_SETUP) { $env:LARRY_SETUP } else { 'C:\larry-setup' }
$Larry  = 'https://larry.home.arpa:11443'
$PiHome = Join-Path $env:USERPROFILE '.pi'
$IsAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
          ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

function Done($k){ Select-String -Path $State -Pattern "^$([regex]::Escape($k))$" -Quiet }
function Mark($k){ if (-not (Done $k)) { Add-Content -Path $State -Value $k } }
function Step($n,$t){ Write-Host "`n[$n] $t" -ForegroundColor Cyan }
function Ok($m){   Write-Host "  [ok] $m"   -ForegroundColor Green }
function Warn($m){ Write-Host "  [!]  $m"   -ForegroundColor Yellow }
function Die($m){  Write-Host "  [x]  $m"   -ForegroundColor Red; exit 1 }
function Say($m){  Write-Host "  $m" }
function Ask($p){  Read-Host "  $p" }
function Pause($m='press Enter when done'){ Read-Host "  $m" | Out-Null }
function YesNo($p){ (Read-Host "  $p [y/N]") -match '^[Yy]' }
# symlink if possible (needs admin / Developer Mode), else copy with a note
function Link($src,$dst){
  if (-not (Test-Path $src)) { return }
  $dir = Split-Path $dst; if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  if (Test-Path $dst) { Remove-Item $dst -Force }
  try { New-Item -ItemType SymbolicLink -Path $dst -Target $src -ErrorAction Stop | Out-Null }
  catch { Copy-Item $src $dst -Force; $script:CopiedNotSymlinked = $true }
}

Write-Host "== Windows -> Larry thin-client wizard ==" -ForegroundColor Cyan
Say "Automates tower/windows-host-setup.md. [HUMAN] steps need you (cert, sign-in)."
Say ("Admin shell: {0}   Setup repo: {1}   State: {2}" -f $IsAdmin, $Repo, $State)
if (-not $IsAdmin) { Warn "Not elevated — CA trust / machine env / symlinks will need an admin shell." }

# --- package manager ------------------------------------------------------------
$Winget = [bool](Get-Command winget -ErrorAction SilentlyContinue)
$Choco  = [bool](Get-Command choco  -ErrorAction SilentlyContinue)
function Install($wingetId,$chocoId){
  if ($Winget) { winget install --accept-source-agreements --accept-package-agreements --id $wingetId -e }
  elseif ($Choco) { choco install -y $chocoId }
  else { Die "neither winget nor choco found — install one, or install '$wingetId' manually, then re-run" }
}

# --- 0. preflight ---------------------------------------------------------------
Step 0 'Preflight'
Say ("winget: {0}   choco: {1}" -f $Winget, $Choco)
if (-not ($Winget -or $Choco)) { Warn "no package manager detected — installs will be skipped/manual" }

# --- 1. base tools --------------------------------------------------------------
Step 1 'Base tools (git, python, node>=22, go)'
if (Done 'base') { Ok 'already done' } else {
  if (-not (Get-Command git    -ErrorAction SilentlyContinue)) { Install 'Git.Git' 'git' }
  if (-not (Get-Command python -ErrorAction SilentlyContinue)) { Install 'Python.Python.3.12' 'python' }
  $nodeMajor = 0
  if (Get-Command node -ErrorAction SilentlyContinue) { $nodeMajor = [int]((node -v) -replace '^v(\d+).*','$1') }
  if ($nodeMajor -lt 22) { Install 'OpenJS.NodeJS.LTS' 'nodejs-lts' }
  if (-not (Get-Command go -ErrorAction SilentlyContinue)) { Install 'GoLang.Go' 'golang' }
  Say "open a fresh shell if PATH for new tools isn't live yet."
  Mark 'base'; Ok 'base tools installed (verify: node -v >= v22)'
}

# --- 2. DNS ---------------------------------------------------------------------
Step 2 'Resolve larry.home.arpa (Pi-hole on the home LAN)'
$dnsOk = $false
try { $r = Resolve-DnsName larry.home.arpa -ErrorAction Stop; $dnsOk = $true; Ok "resolves -> $($r[0].IPAddress)"; Mark 'dns' }
catch {
  Warn "larry.home.arpa does NOT resolve — off the home LAN, or Pi-hole isn't your DNS."
  Say "Fallback: add '192.168.0.173 larry.home.arpa' to C:\Windows\System32\drivers\etc\hosts (elevated),"
  Say "or set up WireGuard (step 11). Claude escalation still works anywhere."
  if (-not (YesNo 'Continue anyway (finish now, connect to Larry later)?')) { Die 'stopping — rejoin LAN and re-run' }
}

# --- 3. HomeLab CA trust --------------------------------------------------------
Step 3 'Trust the HomeLab CA   [HUMAN: supply ca.crt]'
if (Done 'ca') { Ok 'already done' }
elseif (-not $dnsOk) { Warn 'skipped — no Larry reachable yet (do this once on-LAN/WG, elevated)' }
else {
  $trusted = $false
  try { Invoke-RestMethod "$Larry/api/version" -TimeoutSec 8 | Out-Null; $trusted = $true } catch {}
  if ($trusted) { Ok 'CA already trusted (HTTPS to Larry works)'; Mark 'ca' }
  elseif (-not $IsAdmin) { Warn 'CA not trusted and shell not elevated — re-run this step in an admin PowerShell' }
  else {
    Say "Copy the PUBLIC ca.crt here (deb: ~/certs/ca/ca.crt). The CA *key* never leaves the deb box."
    $p = Ask 'Path to ca.crt (default .\ca.crt):'; if (-not $p) { $p = '.\ca.crt' }
    if (-not (Test-Path $p)) { Die "not found: $p — copy it over, then re-run" }
    Import-Certificate -FilePath $p -CertStoreLocation Cert:\LocalMachine\Root | Out-Null
    [Environment]::SetEnvironmentVariable('NODE_OPTIONS','--use-system-ca','Machine')
    $env:NODE_OPTIONS = '--use-system-ca'
    try { Invoke-RestMethod "$Larry/api/version" -TimeoutSec 8 | Out-Null; Ok 'chain verified (no cert error)'; Mark 'ca' }
    catch { Die 'still not trusted — confirm this is the HomeLab ROOT cert, then re-run' }
  }
}

# --- 4. clone setup repo (needed for provider + tooling) ------------------------
Step 4 'Clone the larry-setup repo'
if (Test-Path (Join-Path $Repo '.git')) { Ok "already cloned at $Repo"; Mark 'repo' }
elseif (Done 'repo') { Ok 'marked done' }
else {
  if (Get-Command gh -ErrorAction SilentlyContinue) { Say "tip: 'gh auth login' first for the private repo (account drs76)" }
  git clone 'https://github.com/drs76/larry-setup.git' $Repo
  Push-Location $Repo; git config core.autocrlf false; Pop-Location   # .gitattributes only pins LF on the CLIs
  Ok "cloned to $Repo (core.autocrlf=false in-clone)"; Mark 'repo'
}

# --- 5. pi + provider -----------------------------------------------------------
Step 5 'pi coding agent + Larry provider'
if (Done 'pi') { Ok 'already done' } else {
  npm install -g '@earendil-works/pi-coding-agent'
  New-Item -ItemType Directory -Path (Join-Path $PiHome 'agent') -Force | Out-Null
  $prov = Join-Path $Repo 'tower\ollama-provider.ts'
  if (-not (Test-Path $prov)) { Die "provider missing at $prov (is the repo cloned? step 4)" }
  Copy-Item $prov (Join-Path $PiHome 'ollama-provider.ts') -Force
  Ok 'provider copied (0.81 createProvider form — do not hand-edit to legacy)'
  # register the provider (preserve existing keys)
  $sp = Join-Path $PiHome 'agent\settings.json'
  $provPath = Join-Path $PiHome 'ollama-provider.ts'
  $ext = @($provPath); $model = 'qwen3-coder:30b'
  if (Test-Path $sp) {
    try { $ex = Get-Content $sp -Raw | ConvertFrom-Json
          if ($ex.extensions) { $ext = @($ex.extensions); if ($ext -notcontains $provPath) { $ext += $provPath } }
          if ($ex.defaultModel) { $model = $ex.defaultModel } } catch {}
  }
  # hand-build so a single-element extensions list is always a JSON array (5.1 ConvertTo-Json collapses it)
  $extJson = ($ext | ForEach-Object { '"' + ($_ -replace '\\','\\') + '"' }) -join ', '
  "{`n  `"extensions`": [$extJson],`n  `"defaultModel`": `"$model`"`n}" | Set-Content $sp -Encoding UTF8
  Ok "settings.json updated: $sp"
  if (-not $env:NODE_OPTIONS) { $env:NODE_OPTIONS = '--use-system-ca' }
  if ($dnsOk) {
    try { if ((pi --list-models 2>$null) -match 'qwen3-coder') { Ok 'pi sees Larry models over HTTPS' } else { Warn 'pi listed no models — check CA + NODE_OPTIONS (doc troubleshooting)' } }
    catch { Warn 'pi --list-models failed — open a fresh shell (machine NODE_OPTIONS) and retry' }
  } else { Warn 'Larry unreachable — skipping pi model check' }
  Mark 'pi'
}

# --- 6. Claude Code -------------------------------------------------------------
Step 6 'Claude Code sign-in   [HUMAN]'
if (Done 'claude') { Ok 'already done' } else {
  if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    Warn 'claude not found — on a workstation it is usually preinstalled; install Claude Code, then re-run.'
  } else {
    Say "Sign in once: run 'claude', complete the auth prompt (api.anthropic.com, public CA)."
    Say "NOTE: Claude Desktop shares the same ~/.claude root — never run Desktop + CLI on one session at once."
    Pause; Ok ("claude {0}" -f (claude --version 2>$null)); Mark 'claude'
  }
}

# --- 7. tooling: prompts, slash-commands, CLIs, extensions ----------------------
Step 7 'Link prompts / commands / CLIs from the repo'
if (Done 'tooling') { Ok 'already done' } else {
  $script:CopiedNotSymlinked = $false
  $prompts = Join-Path $env:USERPROFILE '.pi\agent\prompts'
  $cmds    = Join-Path $env:USERPROFILE '.claude\commands'
  $bin     = Join-Path $env:USERPROFILE '.local\bin'
  $exts    = Join-Path $env:USERPROFILE '.pi\agent\extensions'
  foreach ($d in @($prompts,$cmds,$bin,$exts)) { if (-not (Test-Path $d)) { New-Item -ItemType Directory -Path $d -Force | Out-Null } }

  foreach ($n in 'al','al-route','go-route','cs-route','spec','handover','warplan','scout','bc-agent','wizard') {
    Link (Join-Path $Repo "tooling\$n.md") (Join-Path $prompts "$n.md") }
  # Claude slash-commands: *-claude.md entries install under the bare name
  $cmdMap = @{ 'al'='al'; 'fable'='fable'; 'bc-agent'='bc-agent';
               'warplan-claude'='warplan'; 'scout-claude'='scout'; 'spec-claude'='spec'; 'wizard-claude'='wizard' }
  foreach ($k in $cmdMap.Keys) {
    $src = Join-Path $Repo "tooling\$k.md"; if (-not (Test-Path $src)) { $src = Join-Path $Repo "tooling\$($cmdMap[$k]).md" }
    Link $src (Join-Path $cmds "$($cmdMap[$k]).md") }
  foreach ($c in 'alw','gow','csw','probe','bcw','anon','kb','kb-lint','al-rag') {
    Link (Join-Path $Repo "tooling\$c") (Join-Path $bin $c) }
  foreach ($e in 'kb-search','searxng-search') {
    Link (Join-Path $Repo "tooling\$e.pi-ext.ts") (Join-Path $exts "$e.ts") }

  if ($script:CopiedNotSymlinked) { Warn "some items COPIED (symlink needs admin / Developer Mode) — 'git pull' won't auto-update those; re-run this step elevated to symlink." }
  else { Ok 'symlinked (git pull now updates them all)' }
  Mark 'tooling'
}

# --- 8. Git Bash env for the CLIs (~/.bashrc) -----------------------------------
Step 8 'Git Bash env + python3 shim'
if (Done 'bashrc') { Ok 'already done' } else {
  $bashrc = Join-Path $env:USERPROFILE '.bashrc'
  $marker = '# ---------- Larry workflow (Windows host client) ----------'
  $block = @"

$marker
export SETUP_DIR="/c/larry-setup"
export RUN_BUILD="/c/larry-setup/pipeline/run-build.py"
export RUN_BUILD_GO="/c/larry-setup/pipeline/run-build-go.py"
export RUN_BUILD_CS="/c/larry-setup/pipeline/run-build-cs.py"
export TEMPLATE="/c/larry-setup/templates/larry-handover.template.md"
export PROJECTS_DIR="`$HOME/projects"; export PROTOTYPES_DIR="`$HOME/projects/prototypes"
export PI_CODER_MODEL="ollama/qwen3-coder:30b"
export COMS_VALIDATOR_MODEL="ollama/qwen3-coder:30b"; export COMS_RELAY_MODEL="ollama/qwen3-coder:30b"
export NODE_OPTIONS="--use-system-ca"
export PYTHONUTF8=1; export PYTHONIOENCODING=utf-8
export DOTNET_ROOT="`$HOME/.dotnet"
export PATH="`$HOME/.local/bin:`$HOME/AppData/Roaming/npm:`$HOME/.dotnet:`$HOME/.dotnet/tools:`$PATH"
alias python3=python
"@
  if (-not (Test-Path $bashrc) -or -not (Select-String -Path $bashrc -Pattern ([regex]::Escape($marker)) -Quiet)) {
    Add-Content -Path $bashrc -Value $block; Ok "workflow env appended to $bashrc"
  } else { Ok 'env block already present' }
  # python3 shim (LF, no BOM) — scripts that call python3 directly
  $shim = Join-Path $env:USERPROFILE '.local\bin\python3'
  [IO.File]::WriteAllText($shim, "#!/bin/sh`nexec python `"`$@`"`n")
  Ok 'python3 shim written'; Say 'in a Git Bash tab: alw help / gow help / csw help'
  Mark 'bashrc'
}

# --- 9. optional: language referees ---------------------------------------------
Step 9 'Language referees (.NET / AL) — optional'
if (-not (Done 'dotnet') -and (YesNo 'Install .NET 10 SDK (for csw)?')) {
  & ([scriptblock]::Create((Invoke-RestMethod 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 10.0 -InstallDir "$env:USERPROFILE\.dotnet"
  $env:PATH = "$env:USERPROFILE\.dotnet;$env:USERPROFILE\.dotnet\tools;$env:PATH"
  dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org 2>$null
  Ok '.NET 10 installed + nuget.org source added'; Mark 'dotnet'
}
if (-not (Done 'al') -and (YesNo 'Install the AL compiler + .NET 8 runtimes (for alw)?')) {
  & ([scriptblock]::Create((Invoke-RestMethod 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 8.0 -Runtime dotnet     -InstallDir "$env:USERPROFILE\.dotnet"
  & ([scriptblock]::Create((Invoke-RestMethod 'https://dot.net/v1/dotnet-install.ps1'))) -Channel 8.0 -Runtime aspnetcore -InstallDir "$env:USERPROFILE\.dotnet"
  dotnet tool install -g Microsoft.Dynamics.BusinessCentral.Development.Tools 2>$null
  Ok 'AL toolchain installed (symbols auto-download at build via al MCP)'; Mark 'al'
}

# --- 10. optional: terminal polish ----------------------------------------------
Step 10 'Windows Terminal + starship — optional'
if (-not (Done 'term') -and (YesNo 'Install Windows Terminal + starship?')) {
  Install 'Microsoft.WindowsTerminal' 'microsoft-windows-terminal'
  Install 'Starship.Starship' 'starship'
  Say "Wire starship into `$PROFILE (see doc §6); add a Git Bash profile: 'C:\Program Files\Git\bin\bash.exe -l'."
  Mark 'term'
}

# --- 11. optional: WireGuard roaming --------------------------------------------
Step 11 'WireGuard back home (roaming) — optional   [HUMAN: peer values + GUI import]'
if (-not (Done 'wg') -and (YesNo 'Prepare a WireGuard config to reach Larry off-LAN?')) {
  Say "Install the WireGuard for Windows client (winget install WireGuard.WireGuard), then Import this tunnel."
  Warn "Three values come from an existing peer (phone jellydav / router WG UI): router pubkey, ddns:port, tunnel /24."
  $out = Join-Path $env:USERPROFILE 'larry-wg-template.conf'
  @"
[Interface]
PrivateKey = <GENERATE in the WireGuard GUI, or 'wg genkey'>
Address    = 10.0.0.TODO/32          # TODO(human): next free tunnel IP (check a jellydav peer)
DNS        = 192.168.0.175           # Pi-hole (Nemesis) -> larry.home.arpa

[Peer]
PublicKey  = TODO_ROUTER_WG_PUBKEY   # TODO(human): same [Peer] PublicKey as jellydav/phone
Endpoint   = TODO_DDNS_HOST:TODO_PORT # TODO(human): same public endpoint jellydav uses
AllowedIPs = 192.168.0.0/24          # split-tunnel: home LAN only (0.0.0.0/0 = full tunnel)
PersistentKeepalive = 25
"@ | Set-Content $out -Encoding ASCII
  Ok "template written: $out — fill the TODO(human) lines, Import into WireGuard, add this box's pubkey as a router peer, Activate."
  Mark 'wg'
}

# --- done -----------------------------------------------------------------------
Write-Host "`n== done ==" -ForegroundColor Green
Say 'Open a FRESH shell so machine env (NODE_OPTIONS) is live.'
Say 'PowerShell:  pi -p "reply with exactly: OK"'
Say 'Git Bash:    gow new win-smoke; gow build win-smoke   # -> RESULT: PASS'
Say 'Not covered: full AL app.json/runtime specifics (doc §9), terminal wiring (§6).'
Say 'Re-run this wizard any time — completed steps are skipped.'
